### ISSUE TITLE
[Documentation Bug]: update dependabot workflow and remove node_modules from codebase

### ISSUE THREAD

**Issue by Anmol-Baranwal** [kunjgit/GameZone#2597]
### Describe the bug ✍️

- remove `node_modules` directory from `.github`
- update dependabot workflow: it should have a proper commit prefix according to conventions, such as `chore(deps)`. Additionally, it lacks a label, which could be helpful for someone looking at the PR, like `📦 dependencies`.

> Current One:

```yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
```

### Provide step by step information reproduce the bug 📄

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/5f7ae417-b0d8-44bc-89e0-0ba02621979e)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.
